import json
import heapq
from typing import Dict, List, Tuple

class LoadOptimizer:
    def __init__(self):
        self.cluster_map = {}  # Will be loaded from cluster_map.json
        self.load_balance_request = None  # Will be loaded from load_balance_request.json if exists
        
    def load_cluster_map(self):
        """Load the cluster map generated by the Usage Profiler"""
        try:
            with open(r'C:\volt_mesh_output\cluster_map.json', 'r') as f:
                self.cluster_map = json.load(f)
            # Convert string keys back to integers
            self.cluster_map = {int(k): v for k, v in self.cluster_map.items()}
            print("Load Optimizer (The Searcher) loaded cluster map from Usage Profiler")
        except FileNotFoundError:
            print("Warning: cluster_map.json not found. Using default moderate zones.")
            # Default to all moderate if no cluster map exists
            self.cluster_map = {hour: 'Moderate' for hour in range(24)}
    
    def check_for_load_balance_request(self):
        """Check if the Reliability Sentinel has triggered a load balance request"""
        try:
            with open(r'C:\volt_mesh_output\load_balance_request.json', 'r') as f:
                self.load_balance_request = json.load(f)
            print(f"Load Optimizer received load balance request: {self.load_balance_request['triggered']}")
            return self.load_balance_request['triggered']
        except FileNotFoundError:
            return False
    
    def greedy_best_first_search(self, start_hour: int = 0, duration: int = 1) -> Tuple[List[int], float]:
        """
        Greedy Best-First Search to find the lowest-cost hour for heavy appliance usage
        Cost is defined as: Eco=0 (lowest cost), Moderate=1, Peak=2 (highest cost)
        """
        if not self.cluster_map:
            self.load_cluster_map()
        
        # Define cost for each zone
        zone_costs = {'Eco': 0, 'Moderate': 1, 'Peak': 2}
        
        # Priority queue: (cost, hour, path)
        # We're looking for single hour windows, so path is just [hour]
        pq = []
        visited = set()
        
        # Initialize with all hours as potential starting points
        for hour in range(24):
            zone = self.cluster_map.get(hour, 'Moderate')
            cost = zone_costs[zone]
            heapq.heappush(pq, (cost, hour, [hour]))
        
        best_hour = None
        best_cost = float('inf')
        
        # Greedy Best-First Search: expand lowest cost node first
        while pq:
            cost, hour, path = heapq.heappop(pq)
            
            # If we found a better (lower cost) solution
            if cost < best_cost:
                best_cost = cost
                best_hour = hour
                
                # Since we're using a greedy approach and costs are non-negative,
                # the first time we pop from PQ we have the optimal solution
                # But we'll continue to check if there are ties
            
            # If we've visited this hour, skip (for longer paths, but we're doing 1-hour)
            if hour in visited:
                continue
            visited.add(hour)
            
            # For 1-hour window, we don't expand further
            # But for completeness in GBFS, we could check neighbors
            # In this case, we're just evaluating each hour independently
        
        if best_hour is not None:
            best_zone = self.cluster_map.get(best_hour, 'Moderate')
            return [best_hour], best_cost, best_zone
        else:
            return [], float('inf'), None
    
    def find_optimal_heavy_appliance_window(self) -> Dict:
        """Find the optimal 1-hour window for heavy appliance usage"""
        # Check if we should run optimization (triggered by Sentinel)
        if not self.check_for_load_balance_request():
            # If no request, we can still run optimization proactively
            print("No active load balance request. Running proactive optimization...")
        
        # Perform Greedy Best-First Search
        best_hours, cost, zone = self.greedy_best_first_search()
        
        result = {
            'optimal_hours': best_hours,
            'cost': cost,
            'zone': zone,
            'recommendation': f"Schedule heavy appliances during hour {best_hours[0]} ({zone} zone)" if best_hours else "No optimal window found"
        }
        
        return result
    
    def generate_efficiency_audit(self) -> str:
        """Generate a Markdown Efficiency Audit report"""
        result = self.find_optimal_heavy_appliance_window()
        
        audit = f"""# Volt-Mesh Load Optimizer Efficiency Audit

## Overview
The Load Optimizer (The Searcher) has analyzed the power usage patterns to identify optimal times for heavy appliance operation.

## Analysis Results
- **Optimal Hour**: {result['optimal_hours'][0] if result['optimal_hours'] else 'None'} 
- **Usage Zone**: {result['zone'] if result['zone'] else 'Unknown'}
- **Cost Score**: {result['cost']} (Lower is better: Eco=0, Moderate=1, Peak=2)

## Recommendation
{result['recommendation']}

## Load Balance Request Status
{"**ACTIVE** - High overload probability detected by The Predictor" if self.load_balance_request and self.load_balance_request['triggered'] else "**NORMAL** - No immediate overload risk"}

## Notes
- Heavy appliances should be scheduled during 'Eco' zones for minimum cost and grid stress
- If 'Eco' zones are unavailable, 'Moderate' zones are preferred over 'Peak' zones
- This recommendation is based on historical usage patterns from the dataset

---
*Generated by Volt-Mesh Load Optimizer (The Searcher)*
"""
        
        return audit

if __name__ == "__main__":
    # Initialize optimizer
    optimizer = LoadOptimizer()
    
    # Generate and print efficiency audit
    audit_report = optimizer.generate_efficiency_audit()
    print(audit_report)
    
    # Also save to file
    with open(r'C:\volt_mesh_output\efficiency_audit.md', 'w') as f:
        f.write(audit_report)
    
    print("\nSUCCESS: Efficiency audit saved to 'C:\\volt_mesh_output\\efficiency_audit.md'")